### ISSUE TITLE
Docker on Synology

### ISSUE THREAD

**Issue by joakyhsf69** [stossy11/JITStreamer-2.0#13]
Hi, I've been trying to install the server in a container inside my synology NAS. When I run the first command in the guide, it gives an error and doesn't create the pairing file. What could be the problem? Is it not possible to get it working on a Synology? Thanks

```
Joaky@DiskStationFive:/volume1/docker/JitStreamer$ sudo docker run -it --rm -v ${PWD}/:/root/.pymobiledevice3/ -v /var/run:/var/run --cap-add=NET_ADMIN --network=host ghcr.io/stossy11/jitstreamer-2.0 --pair
Password:
Attempting to pair to a device! (Ctrl+C to stop)
Traceback (most recent call last):
  File "/usr/local/bin/JITStreamer", line 8, in <module>
    sys.exit(start_server())
             ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/JITStreamer-2.0/JITStreamer/__init__.py", line 415, in start_server
    devices = select_devices_by_connection_type(connection_type='USB')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 448, in select_devices_by_connection_type
    for device in list_devices(usbmux_address=usbmux_address):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 410, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 406, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
    self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Joaky@DiskStationFive:/volume1/docker/JitStreamer$```

**Comment by stossy11** [comment]
You need usbmuxd installed. (and the pairing should be done on another computer)

**Comment by joakyhsf69** [comment]
I'm sorry, but I don't know how to install usbmuxd. I've also tried to pair it with a computer where the server works fine, I've copied the contents of the /.pymobiledevice3/ folder to the container, the server gives the same error in bash but ends up starting. When I run the shortcut on the mobile it gives an error that the device is not found.

**Comment by EnderRobber101** [comment]
Try using chat gpt and describe you situation, it might help
