### ISSUE TITLE
Executable spamming the console with the same error

### ISSUE THREAD

**Issue by TheAJLive** [stossy11/JITStreamer-2.0#17]
When opening the executable it just keeps sending this error:

ERROR:pymobiledevice3.tunneld:got exception from start-tunnel-task-usbmux-00008140-0011595114F3001C-Network: Traceback (most recent call last):
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\tunneld.py", line 207, in start_tunnel_task
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\contextlib.py", line 210, in __aenter__
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\tunnel_service.py", line 1012, in start_tunnel
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\contextlib.py", line 210, in __aenter__
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\tunnel_service.py", line 926, in start_tcp_tunnel
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\tunnel_service.py", line 298, in start_tunnel
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\tunnel_service.py", line 179, in start_tunnel
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pytun_pmd3\wintun.py", line 222, in __init__
pytun_pmd3.exceptions.PyWinTunException: Failed to create adapter. Last error: 0

I have no idea why this is happening please help.

**Comment by TheAJLive** [comment]
Traceback (most recent call last):
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\launch.py", line 27, in <module>
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\click\core.py", line 1157, in __call__
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\click\core.py", line 1078, in main
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\click\core.py", line 1434, in invoke
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\click\core.py", line 783, in invoke
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\JITStreamer\__init__.py", line 440, in start_server
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\JITStreamer\__init__.py", line 192, in refresh_devs
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\tunneld.py", line 593, in get_tunneld_devices
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\base_events.py", line 687, in run_until_complete
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\tunneld.py", line 588, in async_get_tunneld_devices
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\tunneld.py", line 627, in _create_rsds_from_tunnels
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\remote_service_discovery.py", line 59, in connect
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\pymobiledevice3\remote\remotexpc.py", line 55, in connect
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\streams.py", line 48, in open_connection
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\base_events.py", line 1121, in create_connection
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\base_events.py", line 1103, in create_connection
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\base_events.py", line 1006, in _connect_sock
  File "C:\Users\ajggo\AppData\Local\JITSTR~1\asyncio\proactor_events.py", line 729, in sock_connect
OSError: [WinError 121] The semaphore timeout period has expired



Also does this when ran as an administrator then nothing else happens.
