### ISSUE TITLE
I get this error after running "Jitstreamer" command in powershell

### ISSUE THREAD

**Issue by hbyonly1** [stossy11/JITStreamer-2.0#2]
(venv) PS C:\Users\hbyan\Documents\Adobe> JITStreamer
INFO:     Started server process [10396]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:51589 - "GET / HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\hbyan\Documents\Adobe\venv\Scripts\JITStreamer.exe\__main__.py", line 7, in <module>
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\JITStreamer-2.0\JITStreamer\__init__.py", line 448, in start_server
    refresh_devs()
  File "C:\Users\hbyan\Documents\Adobe\JITStreamer-2.0\JITStreamer\__init__.py", line 193, in refresh_devs
    tunneld_devices = get_tunneld_devices()
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 494, in get_tunneld_devices
    return get_asyncio_loop().run_until_complete(async_get_tunneld_devices(tunneld_address))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 489, in async_get_tunneld_devices
    return await _create_rsds_from_tunnels(tunnels)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 528, in _create_rsds_from_tunnels
    await rsd.connect()
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\pymobiledevice3\remote\remote_service_discovery.py", line 59, in connect
    await self.service.connect()
  File "C:\Users\hbyan\Documents\Adobe\venv\Lib\site-packages\pymobiledevice3\remote\remotexpc.py", line 54, in connect
    self._reader, self._writer = await asyncio.open_connection(self.address[0], self.address[1])
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1121, in create_connection
    raise exceptions[0]
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1103, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1006, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\proactor_events.py", line 729, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 803, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 599, in finish_connect
    ov.getresult()
OSError: [WinError 121] 信号灯超时时间已到

**Comment by hbyonly1** [comment]
I have made sure I have connected to the VPN on both my Computer and iDevice and they are both using hotspot wifi

**Comment by Legomountain14** [comment]
I had a similar error, but I can't remember how I fixed it. Have you tried rebooting both your PC and iDevice?
This is the best I can think of right now.
