### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by wql308** [stossy11/JITStreamer-2.0#25]
```
sudo docker logs jitstreamer-2.0
INFO:     Started server process [12]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:49151 (Press CTRL+C to quit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/utils.py", line 47, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 144, in monitor_usbmux_task
    for mux_device in usbmux.list_devices():
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 414, in list_devices
    mux = create_mux(usbmux_address=usbmux_address)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 410, in create_mux
    return MuxConnection.create(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 174, in create
    sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
    return SafeStreamSocket(address, family)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
    self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
INFO:     127.0.0.1:50508 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
 * Serving Flask app 'JITStreamer'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
```

Hi,

Currently getting this on Debian 12.0 fresh install (after apt update/upgrade), also on Ubuntu 24.02 fresh.
Currently on Python 3.11 (by default) but also tried 3.10/3.12, it's same.
Uploading file works, I have "OK : Upload completed", but can't find any device if I try to enable JIT from shortcut.

Tried a lot of things but nothing works; what am I missing ?

Btw it's fully working on my Mac, but remote Debian server, can't get it to work...

Thanks.

**Comment by wql308** [comment]
I also note a lot of "501 Not Implemented" errors while uploading the pairing file/or accessing other URLs.

I do not have these errors on my Mac.
