### ISSUE TITLE
{"ERROR":"Device not found!"} tunnel creation failed

### ISSUE THREAD

**Issue by Galliyummy** [stossy11/JITStreamer-2.0#26]
Microsoft Windows [Version 10.0.22631.4460]
(c) Microsoft Corporation. All rights reserved.

C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0>.\venv\Scripts\Activate.bat

(venv) C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0>JITStreamer
C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\websockets\legacy\__init__.py:6: DeprecationWarning: websockets.legacy is deprecated; see https://websockets.readthedocs.io/en/stable/howto/upgrade.html for upgrade instructions
  warnings.warn(  # deprecated in 14.0 - 2024-11-09
C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\uvicorn\protocols\websockets\websockets_impl.py:16: DeprecationWarning: websockets.server.WebSocketServerProtocol is deprecated
  from websockets.server import WebSocketServerProtocol
INFO:     Started server process [17896]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:49151 (Press CTRL+C to quit)
INFO:     127.0.0.1:56477 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
 * Serving Flask app 'JITStreamer'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://192.168.86.250:8080
INFO:werkzeug:Press CTRL+C to quit
INFO:     127.0.0.1:56508 - "GET /start-tunnel?ip=192.168.86.39&udid=#myudid&connection_type=usbmux-tcp HTTP/1.1" 200 OK
INFO:     127.0.0.1:56514 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
INFO:werkzeug:192.168.86.39 - - [03/Dec/2024 00:36:14] "GET /#nothappening/ HTTP/1.1" 404 -
ERROR:pymobiledevice3.tunneld:StreamError details: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0
ERROR:pymobiledevice3.tunneld:StreamError occurred at: Traceback (most recent call last):
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 207, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1012, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 925, in start_tcp_tunnel
    handshake_response = await tunnel.request_tunnel_establish()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in request_tunnel_establish
    return json.loads(CDTunnelPacket.parse(await self._reader.read(self.REQUESTED_MTU)).body)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 404, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2236, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2770, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2843, in _parse
    obj = self.subcon._parsereport(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 964, in _parse
    return stream_read(stream, length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 178, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0

ERROR:pymobiledevice3.tunneld:Tunnel creation failed for UDID: #nt bro
INFO:     127.0.0.1:56515 - "GET /start-tunnel?ip=192.168.86.39&udid=#nope&connection_type=usbmux-tcp HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56525 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
INFO:werkzeug:192.168.86.39 - - [03/Dec/2024 00:36:15] "GET /#udidhere/ HTTP/1.1" 404 -

kinda dont know what the issue is, for some reason its having trouble making the tunnel work

**Comment by Galliyummy** [comment]
never mind i wasnt in an admin window
