### ISSUE TITLE
stream read less than the specified amount (only happens when i run as admin)

### ISSUE THREAD

**Issue by Galliyummy** [stossy11/JITStreamer-2.0#27]
ERROR:pymobiledevice3.tunneld:StreamError details: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0
ERROR:pymobiledevice3.tunneld:StreamError occurred at: Traceback (most recent call last):
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 207, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1012, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 925, in start_tcp_tunnel
    handshake_response = await tunnel.request_tunnel_establish()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in request_tunnel_establish
    return json.loads(CDTunnelPacket.parse(await self._reader.read(self.REQUESTED_MTU)).body)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 404, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2236, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2770, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2843, in _parse
    obj = self.subcon._parsereport(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 964, in _parse
    return stream_read(stream, length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 178, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0

ERROR:pymobiledevice3.tunneld:StreamError details: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0
ERROR:pymobiledevice3.tunneld:StreamError occurred at: Traceback (most recent call last):
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\tunneld.py", line 207, in start_tunnel_task
    async with start_tunnel(protocol_handler, protocol=protocol) as tun:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 1012, in start_tunnel
    async with protocol_handler.start_tcp_tunnel() as service:
  File "C:\Utilities\python stuff\Python 3.12\Lib\contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 925, in start_tcp_tunnel
    handshake_response = await tunnel.request_tunnel_establish()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\pymobiledevice3\remote\tunnel_service.py", line 295, in request_tunnel_establish
    return json.loads(CDTunnelPacket.parse(await self._reader.read(self.REQUESTED_MTU)).body)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 404, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 416, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2236, in _parse
    subobj = sc._parsereport(stream, context, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2770, in _parse
    return self.subcon._parsereport(stream, context, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 2843, in _parse
    obj = self.subcon._parsereport(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 428, in _parsereport
    obj = self._parse(stream, context, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 964, in _parse
    return stream_read(stream, length, path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jppan\OneDrive\Documents\Desktop\JitStreamer2.0\venv\Lib\site-packages\construct\core.py", line 178, in stream_read
    raise StreamError("stream read less than specified amount, expected %d, found %d" % (length, len(data)), path=path)
construct.core.StreamError: Error in path (parsing) -> magic
stream read less than specified amount, expected 8, found 0

**Comment by whaleboss** [comment]
I have encountered the same problem
It was fixed after I restarted the tailscale
