### ISSUE TITLE
USBMUX issue when running via docker-compose

### ISSUE THREAD

**Issue by pfych** [stossy11/JITStreamer-2.0#32]
I'm attempting to move my JITStreamer setup into a docker container on my NAS and I've run into a few issues. I'm able to have JITStreamer running in a console just fine.

I'm getting the following error logs on container startup:

```
INFO:     Started server process [12]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:49151 (Press CTRL+C to quit)
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/utils.py", line 47, in wrapper
return await f(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/tunneld.py", line 144, in monitor_usbmux_task
for mux_device in usbmux.list_devices():
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 414, in list_devices
mux = create_mux(usbmux_address=usbmux_address)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 410, in create_mux
return MuxConnection.create(usbmux_address=usbmux_address)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 174, in create
sock = MuxConnection.create_usbmux_socket(usbmux_address=usbmux_address)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 167, in create_usbmux_socket
return SafeStreamSocket(address, family)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/pymobiledevice3/usbmux.py", line 111, in __init__
self.sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
INFO:     127.0.0.1:49780 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
* Serving Flask app 'JITStreamer'
* Debug mode: off
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:8080
* Running on http://172.16.11.2:8080
INFO:werkzeug:[33mPress CTRL+C to quit[0m
```

I'm able to successfully upload my plist file, however errors are present. The file is successfully uploaded to my server.

These are the error logs that appear when uploading via the shortcut, I get `{"OK":"File uploaded"}` on successful upload

```
ERROR:pymobiledevice3.tunneld:Error in usbmux-tcp connection: [Errno 111] Connection refused
WARNING:pymobiledevice3.tunneld:No task created for UDID: #######-#########
INFO:     127.0.0.1:36852 - "GET /start-tunnel?ip=127.0.0.1&udid=#######-#########&connection_type=usbmux-tcp HTTP/1.1" 501 Not Implemented
```

When attempting to enable JIT I get the following output:

```
ERROR:pymobiledevice3.tunneld:Error in usbmux-tcp connection: [Errno 111] Connection refused
WARNING:pymobiledevice3.tunneld:No task created for UDID: #######-#########
INFO:     127.0.0.1:53756 - "GET /start-tunnel?ip=127.0.0.1&udid=#######-#########&connection_type=usbmux-tcp HTTP/1.1" 501 Not Implemented
INFO:     127.0.0.1:53772 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
INFO:werkzeug:127.0.0.1 - - [21/Dec/2024 08:24:30] "[33mGET /#######-#########/ HTTP/1.1[0m" 404 -
2024-12-21 08:24:30.120341+00:00ERROR:pymobiledevice3.tunneld:Error in usbmux-tcp connection: [Errno 111] Connection refused
WARNING:pymobiledevice3.tunneld:No task created for UDID: #######-#########
INFO:     127.0.0.1:53786 - "GET /start-tunnel?ip=127.0.0.1&udid=#######-#########&connection_type=usbmux-tcp HTTP/1.1" 501 Not Implemented
INFO:     127.0.0.1:53790 - "GET / HTTP/1.1" 200 OK
WARNING:root:No devices returned from get_tunneld_devices().
```

My Docker Compose file on my server is as follows:

```yml
services:
  jitstreamer:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: jitstreamer-2.0
    image: ghcr.io/stossy11/jitstreamer-2.0
    restart: always
    volumes:
      - /mnt/dataset/JITStreamer/AppData:/root/.pymobiledevice3/
      - /mnt/dataset/JITStreamer/AppData:/var/run
  tailscale:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    container_name: tailscale-jitstreamer
    depends_on:
      - jitstreamer
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
    image: tailscale/tailscale
    network_mode: service:jitstreamer
    restart: always
    volumes:
      - /mnt/dataset/JITStreamer/AppData:/var/lib/tailscale
```

**Comment by EnderRobber101** [comment]
This worked for me
```
sudo apt update
sudo apt install usbmuxd
sudo systemctl start usbmuxd
sudo systemctl restart usbmuxd

``` 
Also reboot/restart docker container after.
I did it in a proxmox lxc
